title: Konvert
description: Usage documentation of Konvert
theme: just-the-docs
baseurl: "/konvert"

url: https://mcarleio.github.io

aux_links:
  Konvert Repository: https://github.com/mcarleio/konvert

color_scheme: wider

callouts:
  info:
    title: Info
    color: blue

exclude:
  - src/
  - build.gradle.kts
  - build/
  - typeconverter/gen

asciidoctor:
  base_dir: :docdir
  safe: unsafe
  attributes:
    - source-highlighter=rouge
    - showtitle=@
    - github=https://github.com/mcarleio/konvert
    - konvertVersion=2.4.0
